@startuml
left to right direction
actor "Etudiant" as fc
rectangle GestionEtudiants {
  usecase "Enregistrer leur présence" as UC1
  usecase "Consulter leur historique de présence" as UC2
  usecase "Consulter les informations de leur profil" as UC3
  usecase "Signaler une absence" as UC4
  usecase "Vérifier les horaires de cours " as UC5
  usecase "Recevoir des alertes de présence " as UC6
  usecase "Consulter les notifications d'absence" as UC7
  usecase "Signaler un retard" as UC8
  usecase "Consulter les statistiques de sa présence " as UC9
  usecase "Interagir avec les autres étudiants" as UC10
  usecase "S'authentifier" as UC0
} 
(UC1) ..> (UC0) : include
(UC2) ..> (UC0) : include
(UC3) ..> (UC0) : include
(UC4) ..> (UC0) : include
(UC5) ..> (UC0) : include
(UC6) ..> (UC0) : include
(UC7) ..> (UC0) : include
(UC8) ..> (UC0) : include
(UC9) ..> (UC0) : include
(UC10) ..> (UC0) : include
fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4
fc --> UC5
fc --> UC6
fc --> UC7
fc --> UC8
fc --> UC9
fc --> UC10
@enduml
