
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:4306/ENSIASAttendEase
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:       
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true